# Generated by Django 5.1.5 on 2025-03-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
